language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS admportal;" -uroot
  - mysql -e "GRANT ALL ON admportal.* TO travis;" -uroot
  - mysql -e "GRANT ALL ON admportal.* TO travis@localhost;" -uroot
  - mysql -e "GRANT ALL ON admportal.* to admportal_user identified by 'admportal_pass';" -uroot
  - mysql -e "GRANT ALL ON admportal.* to admportal_user@localhost identified by 'admportal_pass';" -uroot
script:
  - ant
