language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS admportal;" -u travis
  - mysql -e "GRANT ALL ON admportal.* TO travis;" -u travis
  - mysql -e "GRANT ALL ON admportal@localhost TO travis;" -u travis
script:
  - ant
